### ISSUE TITLE
Must specify FLAG_IMMUTABLE or FLAG_MUTABLE on PendingIntent for Android 12

### ISSUE THREAD

**Issue by mcezat** [urbanairship/android-gimbal-adapter#25]
After working around [this issue](https://github.com/urbanairship/android-gimbal-adapter/issues/24) by overriding the receiver in the app manifest and adding the exported attribute, this crash is seen after calling `Gimbal.setApiKey()` when running on an Android 12 device:

`Caused by: java.lang.IllegalArgumentException: [app package name withheld]: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at a.b.a.b.h.v.j.e.a(SourceFile:33)
        at a.b.a.b.h.v.j.e.<init>(SourceFile:2)
        at a.b.a.b.h.v.j.e.b(SourceFile:2)
        at a.b.a.b.h.s.d.<init>(SourceFile:6)
        at a.a.e.d.a(SourceFile:434)
        at a.a.e.d.a(SourceFile:794)
        at com.gimbal.android.Gimbal.setApiKey(SourceFile:1)`

**Comment by rlepinski** [comment]
This is another Gimbal issue. Ill forward to the Gimbal team.

**Comment by jyaganeh** [comment]
This is also fixed in version `7.2.0`.
See: https://github.com/urbanairship/android-gimbal-adapter/issues/24#issuecomment-898727083
