### ISSUE TITLE
SDK crashes when trying to start Gimbal with Gimbal SDK 3.0 for Android 8.0

### ISSUE THREAD

**Issue by roman-tikonov** [urbanairship/android-gimbal-adapter#6]
After we integrated android-gimbal-adapter into our app, the GimbalAdapter causes a crash on app start.

android-gimbal-adapter: 2.0
UA SDK: 9.0
Gimbal SDK: **3.0**
Affected Android OS version: **8.0.0 only**

We call this code in our Application.onCreate():
`
GimbalAdapter.shared(context).startWithPermissionPrompt(context.getResources().getString(R.string.gimbal_api_key));
`

Stacktrace:
`
Fatal Exception: android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to register to receive intents
       at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:113)
       at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:102)
       at com.gimbal.internal.receiver.GimbalBroadcastReceiver.a(SourceFile:57)
       at com.gimbal.internal.receiver.GimbalBroadcastReceiver.c(SourceFile:28)
       at com.gimbal.internal.f.(SourceFile:35106)
       at com.gimbal.internal.f.a(SourceFile:73)
       at com.gimbal.internal.d.a(SourceFile:17)
       at com.gimbal.internal.d.a(SourceFile:21)
       at com.gimbal.android.Gimbal.setApiKey(SourceFile:19)
       at com.urbanairship.gimbal.GimbalAdapter.startAdapter(GimbalAdapter.java:265)
       at com.urbanairship.gimbal.GimbalAdapter.access$000(GimbalAdapter.java:38)
       at com.urbanairship.gimbal.GimbalAdapter$2.onResult(GimbalAdapter.java:242)
       at com.urbanairship.gimbal.GimbalAdapter$RequestPermissionsTask.onPostExecute(GimbalAdapter.java:373)
       at com.urbanairship.gimbal.GimbalAdapter$RequestPermissionsTask.onPostExecute(GimbalAdapter.java:347)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.-wrap1(Unknown Source)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:180)
       at android.app.ActivityThread.main(ActivityThread.java:6950)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
`

**Comment by rlepinski** [comment]
@roman-tikhonov Thanks for the report. Gimbal fixed this crash in the Gimbal SDK 3.1.1 release. You can either define that dependency in your build.gradle file to force the adapter to use the newer SDK or wait for tomorrow when I push a release that bumps the SDK version.

**Comment by rlepinski** [comment]
Fixed in 2.0.1
